export const partnersData = [
  {
    id: 1,
    name: "StealthEX",
    logo: "/pione-chain/partners/stealthex.jpg",
    category: "Exchange Partner",
    categoryIcon: "mdi:swap-horizontal-bold",
    description: "ecosystem.card26.description",
    website: "https://stealthex.io",
    socials: {
      twitter: "https://x.com/StealthEX_io",
      telegram: "https://t.me/StealthEX",
      youtube: "https://www.youtube.com/channel/UCeES_XBesX76ge7xf1meuSw",
      facebook: "",
    },
  },
  {
    id: 2,
    name: "PinkSale",
    logo: "/pione-chain/partners/pinkSale.png",
    category: "Exchange Partner",
    categoryIcon: "mdi:swap-horizontal-bold",
    description: "ecosystem.card27.description",
    website: "https://stealthex.io",
    socials: {
      twitter: "https://x.com/pinkecosystem",
      telegram: "https://t.me/pinkecosystem",
      youtube: "",
      facebook: "https://www.facebook.com/pinkecosystem/",
    },
  },
  {
    id: 3,
    name: "DEXView",
    logo: "/pione-chain/partners/dexView.png",
    category: "Exchange Partner",
    categoryIcon: "mdi:swap-horizontal-bold",
    description: "ecosystem.card28.description",
    website: "https://stealthex.io",
    socials: {
      twitter: "",
      telegram: "https://t.me/dexview",
      youtube: "",
      facebook: "",
    },
  },
  {
    id: 4,
    name: "PioneWallet",
    logo: "/pione-chain/logos/pionewallet.svg",
    category: "Wallet Partner",
    categoryIcon: "mdi:wallet-outline",
    description: "ecosystem.card9.description",
    website: "https://pionewallet.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 5,
    name: "Pione House",
    logo: "/pione-chain/logos/pionehouse.svg",
    category: "Blockchain Partner",
    categoryIcon: "mdi:shield-outline",
    description: "ecosystem.card2.description",
    website: "https://pionehouse.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 6,
    name: "Pione AI",
    logo: "/pione-chain/logos/pioneai.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card11.description",
    website: "https://pioai.net/",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 7,
    name: "Pione Dream",
    logo: "/pione-chain/logos/pionedream.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card16.description",
    website: "https://pionedream.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 8,
    name: "Pione Care",
    logo: "/pione-chain/logos/pionecare.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card8.description",
    website: "https://pionecare.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 9,
    name: "Pione Mart",
    logo: "/pione-chain/logos/pionemart.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card5.description",
    website: "https://pionemart.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 10,
    name: "Pione Swap",
    logo: "/pione-chain/logos/pioneswap.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card10.description",
    website: "https://pioneswap.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 11,
    name: "Pione Farm",
    logo: "/pione-chain/logos/pionefarm.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card6.description",
    website: "https://pioneswap.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
  {
    id: 12,
    name: "Ex Pione",
    logo: "/pione-chain/logos/expione.svg",
    category: "Public Blockchain Partner",
    categoryIcon: "mdi:globe-model",
    description: "ecosystem.card4.description",
    website: "https://pioneswap.com",
    socials: {
      twitter: "https://x.com/pione_chain",
      telegram: "https://t.me/pionechain",
      youtube: "https://www.youtube.com/@pione_chain",
      facebook: "",
    },
  },
];
